import React from 'react';

// Simple iframe embed against the public meet.jit.si server — no API key
// or server-side room provisioning needed, which matches this session's
// meetingProvider default ('jitsi') and jitsiRoom name generated by
// liveSessionsController.js (deterministic per session id, so nothing
// has to be created/stored ahead of time).
export default function JitsiEmbed({ room, displayName, onClose }){
  const src = `https://meet.jit.si/${encodeURIComponent(room)}#userInfo.displayName=%22${encodeURIComponent(displayName || 'SkillSwap User')}%22&config.prejoinPageEnabled=true`;

  return (
    <div className="jitsi-embed-wrap">
      <div className="jitsi-embed-bar">
        <span>🔴 Live session in progress</span>
        {onClose && <button className="btn-ghost-lg" onClick={onClose}>Leave</button>}
      </div>
      <iframe
        title="Live session"
        src={src}
        allow="camera; microphone; fullscreen; display-capture; autoplay"
        className="jitsi-embed-frame"
      />
    </div>
  );
}
